version: 2
jobs:
  build:
    docker:
      - image: amazonlinux
    steps:
      - checkout
      - run:
          name: Get Pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
      - run:
          name: Setup Environment Variables
          command: |
            echo "export AWS_DEFAULT_REGION=us-west-2" >> $BASH_ENV
            echo "export IMAGE_REPO_NAME=ghc" >> $BASH_ENV
            echo "export AWS_ACCOUNT_ID=502627520384" >> $BASH_ENV
            echo "export IMAGE_TAG=$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - run:
          name: Build image and push to ECR
          command: |
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          environment:
            AWS_DEFAULT_REGION: "us-west-2"
            AWS_ACCOUNT_ID: "502627520384"
            IMAGE_REPO_NAME: "ghc"
            IMAGE_TAG: "$CIRCLE_BUILD_NUM"
  test:
    docker:
      - image: amazonlinux
    steps:
      - checkout
      - run:
          name: Get Pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
      - run:
          name: Pip install
          command: |
            pip install awscli
      - run:
          name: Validate CFN templates
          command: |
            for i in cfn/*.yml; do aws cloudformation validate-template --template-body file://$i --region us-west-2 ; done
  deploy:
    docker:
      - image: amazonlinux
    steps:
      - checkout
      - run:
          name: Get Pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
      - run:
          name: Pip install
          command: |
            pip install awscli
      - run:
          name: Deploy Shared Resources
          command: |
            if ! aws cloudformation describe-stacks --stack-name ghc-workshop-shared-resources --region us-west-2 ;  then
              aws cloudformation deploy --stack-name ghc-workshop-shared-resources --template-file cfn/shared_resources.yml --capabilities CAPABILITY_NAMED_IAM --parameter-overrides WorkshopName="ghc-workshop" --region us-west-2
            else
              echo -e "Stack exists..."
            fi
          no_output_timeout: 20m
      - run:
          name: Deploy Application
          command: |
            aws cloudformation deploy --stack-name ghc-workshop-application-$CIRCLE_PROJECT_USERNAME --template-file cfn/application.yml --parameter-overrides SharedResourceStack="ghc-workshop-shared-resources" --region us-west-2 || exit 0
          no_output_timeout: 20m
workflows:
  version: 2
  build_approve_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approve
